.install_dependencies_job:
  script:
    - apk add git libc6-compat
    - corepack enable
    # Fix for error: Failed to set up Chrome r115.0.5790.98! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download
    - export PUPPETEER_SKIP_DOWNLOAD=true
    - export NX_ISOLATE_PLUGINS=false
    - pnpm config set store-dir .pnpm-store
    - pnpm install
    - pnpm store path

.install_and_prepare_aws_cli_job:
  script:
    - apk add --no-cache python3 py3-pip jq
    - pip3 install --upgrade pip  --break-system-packages
    - pip3 install awscli  --break-system-packages
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_DEFAULT_REGION

.install_and_prepare_docker:
  script:
    - apk add --no-cache jq docker openrc aws-cli
    - rc-update add docker boot

.set_node_environment_variables:
  script:
    - export NODE_OPTIONS=--max-old-space-size=4096

.install_bash_and_prepare_version_variable:
  script:
    - apk add --no-cache --upgrade bash
    - chmod +x ./misc/gitlab-ci/shared/prepare-release-version.sh
    - export PREPARED_RELEASE_VERSION=`./misc/gitlab-ci/shared/prepare-release-version.sh`
    - echo $PREPARED_RELEASE_VERSION

.install_docker:
  script:
    - apk add --no-cache docker openrc
    - rc-update add docker boot
