image: node:17-alpine

stages:
  - lint-test-build
  - deployment

variables:
  REGISTRY: git.freshcode.org:4567/pradev/boilerplate-v2
  BRANCH_IMAGE: $REGISTRY:$CI_COMMIT_REF_SLUG
  PNPM_INSTALL_COMMAND: pnpm install --store-dir .pnpm-store
  POSTGRES_DB: testing
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST_AUTH_METHOD: trust
  REDIS_PASSWORD: Owc1J4cy3DS0TWn0Afed
  WEB_TAG_REGEX: /^web\/([0-9]+[\.]?)+/
  WEB_MAIN_BRANCH_TAG_REGEX: /^web\/([0-9]+[\.]?)+$/
  WEB_STAGING_BRANCH_TAG_REGEX: /^web\/([0-9]+[\.]?)+(-(staging){1})(-[\d])?$/

lint-test-build:
  stage: lint-test-build
  services:
    - name: bitnami/redis:latest
      alias: redis
    - name: postgres:latest
      alias: postgres
  interruptible: true
  variables:
    NX_DATABASE_HOST: postgres
    NX_TEST_DATABASE_NAME: $POSTGRES_DB
  script:
    - npm install -g pnpm
    - $PNPM_INSTALL_COMMAND
    - pnpm nx run-many --all --target=lint --configuration=ci
    - pnpm nx run-many --all --target=test
    - pnpm run merge-test-reports
    - pnpm nx run-many --all --target=build
  artifacts:
    when: always
    paths:
      - dist
      - __reports__
    reports:
      junit: __reports__/merged.xml
      codequality: __lint__/api.json
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG =~ $WEB_TAG_REGEX

.web-deployment-job:
  image: docker:stable
  stage: deployment
  interruptible: true
  dependencies:
    - lint-test-build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $BRANCH_IMAGE -f ./misc/Dockerfile .
    - docker push $BRANCH_IMAGE

deploy-main:
  extends: .web-deployment-job
  environment:
    name: main
  rules:
    - if: $CI_COMMIT_TAG =~ $WEB_MAIN_BRANCH_TAG_REGEX

create-release-main:
  stage: deployment
  interruptible: true
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  dependencies:
    - deploy-main
  script:
    - echo 'Release creation...'
  release:
    name: 'Web Release $CI_COMMIT_TAG'
    description: 'Created automatically as a result of manual tag creation'
    tag_name: $CI_COMMIT_TAG
    ref: $CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG =~ $WEB_MAIN_BRANCH_TAG_REGEX

deploy-staging:
  extends: .web-deployment-job
  environment:
    name: staging
  rules:
    - if: $CI_COMMIT_TAG =~ $WEB_STAGING_BRANCH_TAG_REGEX
