version: '2'
services:
  postgres:
    image: postgres:16-alpine
    container_name: bp_postgres
    tty: true
    ports:
      - 5442:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=boilerplate
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ../.data/postgres:/var/lib/postgresql/data

#  redis:
#    image: bitnami/redis:7.2
#    container_name: bp_redis
#    tty: true
#    ports:
#      - 6379:6379
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#      - REDIS_REPLICATION_MODE=master
#      - REDIS_PASSWORD=Owc1J4cy3DS0TWn0Afed
#    volumes:
#      - ../.data/redis:/bitnami/redis/data
