version: '2'
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: testing
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432/tcp
  redis:
    image: bitnami/redis:latest
    environment:
      REDIS_PASSWORD: Owc1J4cy3DS0TWn0Afed
    ports:
      - 6379:6379/tcp
