export const ACCESS_TOKEN_COOKIE_KEY = 'ACCESS_TOKEN';
export const REFRESH_TOKEN_COOKIE_KEY = 'REFRESH_TOKEN';

export const AUTH_KEYS_LIST = [ACCESS_TOKEN_COOKIE_KEY, REFRESH_TOKEN_COOKIE_KEY];

export const REFRESH_LOCK_KEY = 'refresh_lock';

