.install_dependencies_job:
  script:
    - apk add git
    - unset $(printenv | grep '^YARN_' | cut -d= -f1)
    - corepack enable
    # Fix for error: Failed to set up Chrome r115.0.5790.98! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download
    - export PUPPETEER_SKIP_DOWNLOAD=true
    # ToDo: Try replace classic yarn with the latest version
    - yarn set version classic
    - yarn

.install_and_prepare_aws_cli_job:
  script:
    - apk add --no-cache python3 py3-pip && pip3 install --upgrade pip && pip3 install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_DEFAULT_REGION

.install_and_prepare_docker:
  script:
    - apk add --no-cache jq docker openrc aws-cli
    - rc-update add docker boot

.install_bash_and_prepare_version_variable:
  script:
    - apk add --no-cache --upgrade bash
    - chmod +x ./misc/gitlab-ci/shared/prepare-release-version.sh
    - export PREPARED_RELEASE_VERSION=`./misc/gitlab-ci/shared/prepare-release-version.sh`
    - echo $PREPARED_RELEASE_VERSION

.install_docker:
  script:
    - apk add --no-cache docker openrc
    - rc-update add docker boot
